apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bridge-bsos-tech
  region: ap-northeast-1

nodeGroups:
  - name: bsos-tech
    instanceType: t3.medium
    desiredCapacity: 4
    volumeSize: 32
    volumeType: gp2
    ssh: # import public key from file
      publicKeyPath: ~/.ssh/id_rsa.pub

