apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    node.number: "3"
    node.current: "_NODE_ID_"
  creationTimestamp: null
  labels:
    name: node-_NODE_ID_
  name: node-_NODE_ID_
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consortiumchain
        name: node-_NODE_ID_
        service.rpc: node-_NODE_ID_
    spec:
      containers:
      - image: _QUORUM_IMAGE_
        imagePullPolicy: _IMAGE_PULL_POLICY_
        name: node-_NODE_ID_
        command: ["/bin/bash"]
        args:
        - "-cx"
        - |-
          _NODE_SCRIPT_
        ports:
        - containerPort: 8545
        - containerPort: 23000
        - containerPort: 9000
        - containerPort: 30303
        resources: {}
        volumeMounts:
        - name: node-_NODE_ID_
          mountPath: /qdata
        - name: quorum-permissioned-config
          mountPath: /qdata/dd/static-nodes.json
          subPath: static-nodes.json
        - name: genesis-config
          mountPath: /qdata/genesis.json
          subPath: genesis.json
        - name: start-config
          mountPath: /qdata/start.sh
          subPath: start.sh
        - name: crux-config
          mountPath: /qdata/tm.conf
          subPath: tm.conf

      restartPolicy: Always
      volumes:
      - name: node-_NODE_ID_
        persistentVolumeClaim:
          claimName: node-_NODE_ID_
      - name: quorum-permissioned-config
        configMap:
          name: quorum-permissioned-config
          items:
            - key: static-nodes.json
              path: static-nodes.json
      - name: genesis-config
        configMap:
          name: genesis-config
          items:
            - key: genesis.json
              path: genesis.json
      - name: start-config
        configMap:
          name: start-config
          items:
            - key: start.sh
              path: start.sh
      - name: crux-config
        configMap:
          name: node-_NODE_ID_-crux-config
          items:
            - key: tm.conf
              path: tm.conf
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    name: node-_NODE_ID_
  name: node-_NODE_ID_
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app: consortiumchain
    version: '1'
  creationTimestamp: null
  labels:
    name: node-_NODE_ID_
  name: node-_NODE_ID_
spec:
  type: LoadBalancer
  clusterIP: "_NODE_IP_"
  ports:
  - name: rpc
    nodePort: 3170_NODE_ID_
    port: 8545
    targetPort: 8545
  - name: raft
    port: 23000
    targetPort: 23000
  - name: constellation
    port: 9000
    targetPort: 9000
  - name: tx
    port: 30303
    targetPort: 30303
  selector:
    service.rpc: node-_NODE_ID_
status:
  loadBalancer: {}
---
