apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-permissioned-config
  labels:
    name: quorum-permissioned-config
data:
  static-nodes.json: |-
    _STATIC_NODES_

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis-config
  labels:
    name: genesis-config
data:
  genesis.json: |-
    _GENESIS_

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: start-config
  labels:
    name: start-config
data:
  start.sh: |-
    _START_